### ISSUE TITLE
Create a new release to rubygems

### ISSUE THREAD

**Issue by otlaitil** [decioferreira/omniauth-linkedin-oauth2#34]
Hi! Could you please release a new version of the gem including `Fix the oauth 1.4 issuex` commit (that seems to be merged to master already).

**Comment by decioferreira** [comment]
sorry I haven't had time to do this yet, I don't currently have a working environment to do this - I'll try doing it during this week.

In the mean time, I guess you could fork this project and use it on your Gemfile? Thanks

**Comment by PlugIN73** [comment]
@decioferreira hi! Could you release gem now?

**Comment by Zequez** [comment]
@heythisisnate also seems to have permissions at RubyGems. Anyone wants to make a release? Last release it's from 2013 and it's broken (at least for my use case), master seems to work 🙂

**Comment by basicBrogrammer** [comment]
I really need a new release of the master branch. I'm deploying with AWS elasticbeanstalk and its running into a problem pulling from master. Is there anyway I could help releasing a new version of the gem ?

**Comment by heythisisnate** [comment]
I just pushed the gem 0.2.5, this was the latest in master. Tests passed for me locally, but I don't have an app anymore that uses this gem. Can anyone verify that the new gem works?

**Comment by artplan1** [comment]
@heythisisnate all good now, thank you

**Comment by basicBrogrammer** [comment]
Thanks for pushing a new verison! App == Deployed
