### ISSUE TITLE
Authentication failure! invalid_credentials: OAuth2::Error

### ISSUE THREAD

**Issue by tskulkarni25** [decioferreira/omniauth-linkedin-oauth2#53]
I, [2019-04-18T15:01:00.068558 #3923]  INFO -- omniauth: (linkedin) Callback phase initiated.
E, [2019-04-18T15:01:01.774531 #3923] ERROR -- omniauth: (linkedin) Authentication failure! invalid_credentials: OAuth2::Error, : 
{
  "errorCode": 0,
  "message": "This resource is no longer available under v1 APIs",
  "requestId": "4RZES38RSZ",
  "status": 410,
  "timestamp": 1555579861698
}

I am getting above issue. Can someone help?

**Comment by jjmedinas** [comment]
Hi, I'm getting the same issue.
I just created a new app on linkedin with the default permissions and I'm getting:
`(linkedin) Authentication failure! invalid_credentials: OAuth2::Error, :`
```{
  "errorCode": 0,
  "message": "This resource is no longer available under v1 APIs",
  "requestId": "8TSSVV5NNS",
  "status": 410,
  "timestamp": 1555965555058
}```

**Comment by tskulkarni25** [comment]
Hey,
My issue was resolved. Please use this version of the gem => gem 'omniauth-linkedin-oauth2', '1.0.0'.

**Comment by jjmedinas** [comment]
It worked, thank you so much! @tskulkarni25
