### ISSUE TITLE
Does the gem return the refresh token when a token is expired?

### ISSUE THREAD

**Issue by wee007** [decioferreira/omniauth-linkedin-oauth2#54]
@decioferreira  The gem doesn't seem to return the refresh token, which I believe I need it to get a new token when the token is expired.

I debugged my app to see what the omniauth response provides me and I do not see a refresh token returned just the token and the expiry date.

```
Rails.application.config.middleware.use OmniAuth::Builder do
  provider :linkedin, ENV['LINKEDIN_CONSUMER_KEY'], ENV['LINKEDIN_CONSUMER_SECRET'], {
    :scope => ENV['LINKEDIN_SCOPES'],
    :fields => ['id', 'first-name', 'last-name', 'picture-url']
  }
end
```

I'd like to find out if the gem's supposed to return the refresh token? Or does the gem issue me a new token? Or does it extend the expiry date for an existing token?

**Comment by kalemi19** [comment]
From the [docs](https://developer.linkedin.com/docs/Refresh-Tokens-with-OAuth-2#):

> LinkedIn has introduced Refresh Tokens with OAuth 2.0.  This feature is currently available for a limited set of partners. It will be made GA in the near future.
